SELECT_CURRENT_SCHEMA=\
SELECT CURRENT_SCHEMA FROM DUMMY

LIST_GRAPH_WORKSPACES=\
SELECT SCHEMA_NAME, WORKSPACE_NAME FROM GRAPH_WORKSPACES WHERE IS_VALID = 'TRUE'

LOAD_WORKSPACE_METADATA_HANA_CLOUD=\
SELECT ENTITY_TYPE, ENTITY_ROLE, ENTITY_SCHEMA_NAME, ENTITY_TABLE_NAME, ENTITY_COLUMN_NAME \
FROM GRAPH_WORKSPACE_COLUMNS WHERE SCHEMA_NAME = ? AND WORKSPACE_NAME = ?

LOAD_WORKSPACE_METADATA_HANA_ONPREM=\
SELECT ENTITY_TYPE, ENTITY_ROLE, ENTITY_SCHEMA_NAME, ENTITY_TABLE_NAME, ENTITY_COLUMN_NAME FROM \
( \
	SELECT SCHEMA_NAME, WORKSPACE_NAME, 'EDGE' ENTITY_TYPE, 'KEY' ENTITY_ROLE, EDGE_SCHEMA_NAME ENTITY_SCHEMA_NAME, EDGE_TABLE_NAME ENTITY_TABLE_NAME, EDGE_KEY_COLUMN_NAME ENTITY_COLUMN_NAME, IS_VALID FROM GRAPH_WORKSPACES \
	UNION \
	SELECT SCHEMA_NAME, WORKSPACE_NAME, 'EDGE' ENTITY_TYPE, 'SOURCE' ENTITY_ROLE, EDGE_SCHEMA_NAME ENTITY_SCHEMA_NAME, EDGE_TABLE_NAME ENTITY_TABLE_NAME, EDGE_SOURCE_COLUMN_NAME ENTITY_COLUMN_NAME, IS_VALID FROM GRAPH_WORKSPACES \
	UNION \
	SELECT SCHEMA_NAME, WORKSPACE_NAME, 'EDGE' ENTITY_TYPE, 'TARGET' ENTITY_ROLE, EDGE_SCHEMA_NAME ENTITY_SCHEMA_NAME, EDGE_TABLE_NAME ENTITY_TABLE_NAME, EDGE_TARGET_COLUMN_NAME ENTITY_COLUMN_NAME, IS_VALID FROM GRAPH_WORKSPACES \
	UNION \
	SELECT SCHEMA_NAME, WORKSPACE_NAME, 'VERTEX' ENTITY_TYPE, 'KEY' ENTITY_ROLE, VERTEX_SCHEMA_NAME ENTITY_SCHEMA_NAME, VERTEX_TABLE_NAME ENTITY_TABLE_NAME, VERTEX_KEY_COLUMN_NAME ENTITY_COLUMN_NAME, IS_VALID FROM GRAPH_WORKSPACES \
) WHERE SCHEMA_NAME = ? AND WORKSPACE_NAME = ? AND IS_VALID = 'TRUE'

LOAD_NETWORK_NODES=\
SELECT %s %s FROM %s.%s

LOAD_NETWORK_EDGES=\
SELECT %s, %s, %s %s FROM %s.%s